### ISSUE TITLE
Passing an array of objects in the body of a POST generates a bad request

### ISSUE THREAD

**Issue by aniblaze** [kleijnweb/swagger-bundle#78]
When attempting to POST an array of objects, the bundle generates a '400 bad request'. The array of objects is defined as followed in the swagger.yml:

```
    post:
      summary: Random description
      security:
        - bearer: []
      parameters:
        - in: body
          name: ObjectName
          required: true
          schema:
            type: array
            items:
              $ref: '#/definitions/ObjectName'
```

with the object definition looking like this:

```
  ObjectName:
    type: object
    additionalProperties: false
    properties:
      varName:
        type: string
        readOnly: true
```

The issue seems to arise when the JMS serializer wants to parse a NULL value. The following bit is extracted from the stacktrace:

```
#3 /var/www/vendor/jms/serializer/src/JMS/Serializer/Serializer.php(99): JMS\Parser\AbstractParser->parse(NULL)
```

**Comment by kleijnweb** [comment]
@aniblaze: could you include the top part of the backtrace (the actual exception, file and line number)?

**Comment by aniblaze** [comment]
I'll just include the entire formatted stacktrace.

```
JMS\Parser\SyntaxErrorException: Expected T_NAME, but got end of input. in /var/www/vendor/jms/parser-lib/src/JMS/Parser/AbstractParser.php:118 Stack trace: 
#0 /var/www/vendor/jms/parser-lib/src/JMS/Parser/AbstractParser.php(73): JMS\Parser\AbstractParser->syntaxError('T_NAME') 
#1 /var/www/vendor/jms/serializer/src/JMS/Serializer/TypeParser.php(84): JMS\Parser\AbstractParser->match(1) 
#2 /var/www/vendor/jms/parser-lib/src/JMS/Parser/AbstractParser.php(49): JMS\Serializer\TypeParser->parseInternal() 
#3 /var/www/vendor/jms/serializer/src/JMS/Serializer/Serializer.php(99): JMS\Parser\AbstractParser->parse(NULL) 
#4 [internal function]: JMS\Serializer\Serializer->JMS\Serializer\{closure}(Object(JMS\Serializer\JsonDeserializationVisitor)) 
#5 /var/www/vendor/phpoption/phpoption/src/PhpOption/Some.php(89): call_user_func(Object(Closure), Object(JMS\Serializer\JsonDeserializationVisitor)) 
#6 /var/www/vendor/jms/serializer/src/JMS/Serializer/Serializer.php(102): PhpOption\Some->map(Object(Closure)) 
#7 /var/www/vendor/kleijnweb/swagger-bundle/src/Serializer/SerializerAdapter.php(85): JMS\Serializer\Serializer->deserialize('[\n    {\n      "...', NULL, 'json', Object(JMS\Serializer\DeserializationContext)) 
#8 /var/www/vendor/kleijnweb/swagger-bundle/src/Request/ContentDecoder.php(69): KleijnWeb\SwaggerBundle\Serializer\SerializerAdapter->deserialize('[\n    {\n      "...', NULL, 'json') 
#9 /var/www/vendor/kleijnweb/swagger-bundle/src/Request/RequestCoercer.php(43): KleijnWeb\SwaggerBundle\Request\ContentDecoder->decodeContent(Object(Symfony\Component\HttpFoundation\Request), Object(KleijnWeb\SwaggerBundle\Document\OperationObject)) 
#10 /var/www/vendor/kleijnweb/swagger-bundle/src/Request/RequestProcessor.php(52): KleijnWeb\SwaggerBundle\Request\RequestCoercer->coerceRequest(Object(Symfony\Component\HttpFoundation\Request), Object(KleijnWeb\SwaggerBundle\Document\OperationObject)) 
#11 /var/www/vendor/kleijnweb/swagger-bundle/src/EventListener/RequestListener.php(61): KleijnWeb\SwaggerBundle\Request\RequestProcessor->process(Object(Symfony\Component\HttpFoundation\Request), Object(KleijnWeb\SwaggerBundle\Document\OperationObject)) 
#12 [internal function]: KleijnWeb\SwaggerBundle\EventListener\RequestListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher)) 
#13 /var/www/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php(164): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher)) 
#14 /var/www/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php(53): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) 
#15 /var/www/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/ContainerAwareEventDispatcher.php(167): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) 
#16 /var/www/app/bootstrap.php.cache(3043): Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) 
#17 /var/www/app/bootstrap.php.cache(3016): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) 
#18 /var/www/app/bootstrap.php.cache(3165): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) 
#19 /var/www/app/bootstrap.php.cache(2406): Symfony\Component\HttpKernel\DependencyInjection\ContainerAwareHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) 
#20 /var/www/web/app.php(30): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request)) 
#21 {main}  Next KleijnWeb\SwaggerBundle\Exception\MalformedContentException: Unable to decode payload in /var/www/vendor/kleijnweb/swagger-bundle/src/Request/ContentDecoder.php:71 Stack trace: 
```

```
#0 /var/www/vendor/kleijnweb/swagger-bundle/src/Request/RequestCoercer.php(43): KleijnWeb\SwaggerBundle\Request\ContentDecoder->decodeContent(Object(Symfony\Component\HttpFoundation\Request), Object(KleijnWeb\SwaggerBundle\Document\OperationObject)) 
#1 /var/www/vendor/kleijnweb/swagger-bundle/src/Request/RequestProcessor.php(52): KleijnWeb\SwaggerBundle\Request\RequestCoercer->coerceRequest(Object(Symfony\Component\HttpFoundation\Request), Object(KleijnWeb\SwaggerBundle\Document\OperationObject)) 
#2 /var/www/vendor/kleijnweb/swagger-bundle/src/EventListener/RequestListener.php(61): KleijnWeb\SwaggerBundle\Request\RequestProcessor->process(Object(Symfony\Component\HttpFoundation\Request), Object(KleijnWeb\SwaggerBundle\Document\OperationObject)) 
#3 [internal function]: KleijnWeb\SwaggerBundle\EventListener\RequestListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher)) 
#4 /var/www/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php(164): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher)) 
#5 /var/www/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php(53): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) 
#6 /var/www/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/ContainerAwareEventDispatcher.php(167): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) 
#7 /var/www/app/bootstrap.php.cache(3043): Symfony\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch('kernel.request', Object(Symfony\Component\HttpKernel\Event\GetResponseEvent)) 
#8 /var/www/app/bootstrap.php.cache(3016): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) 
#9 /var/www/app/bootstrap.php.cache(3165): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) 
#10 /var/www/app/bootstrap.php.cache(2406): Symfony\Component\HttpKernel\DependencyInjection\ContainerAwareHttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) 
#11 /var/www/web/app.php(30): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request)) 
#12 {main}
```
